<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Audit Trail Report</title>
    @vite(['resources/css/pages/auditpdf.css'])
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h2>Audit Trail Report</h2>
        <p>Generated: {{ $generated_at }}</p>
        <p>Generated By: {{ $generated_by }}</p>
    </div>

    <!-- Filter Summary -->
    <div class="filter-summary">
        <h3>Report Criteria</h3>
        @foreach($filterSummary as $key => $value)
            <p><strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong> {{ $value }}</p>
        @endforeach
    </div>

    <!-- Statistics -->
    <div class="statistics">
        <div class="stat-box">
            <h4>{{ $statistics['total_records'] }}</h4>
            <p>Total Records</p>
        </div>
        <div class="stat-box">
            <h4>{{ $statistics['actions_breakdown']->count() }}</h4>
            <p>Action Types</p>
        </div>
        <div class="stat-box">
            <h4>{{ $statistics['tables_affected']->count() }}</h4>
            <p>Tables Affected</p>
        </div>
        <div class="stat-box">
            <h4>{{ $audits->unique('user_id')->count() }}</h4>
            <p>Unique Users</p>
        </div>
    </div>

    <!-- Actions Breakdown -->
    <h3>Actions Breakdown</h3>
    <table>
        <thead>
            <tr>
                <th>Action</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach($statistics['actions_breakdown'] as $action => $count)
            <tr>
                <td>
                    @php
                        $badgeClass = [
                            'INSERT' => 'badge-success',
                            'UPDATE' => 'badge-info',
                            'DELETE' => 'badge-danger',
                            'LOGIN' => 'badge-primary',
                            'LOGOUT' => 'badge-secondary'
                        ][$action] ?? 'badge-secondary';
                    @endphp
                    <span class="badge {{ $badgeClass }}">{{ $action }}</span>
                </td>
                <td>{{ $count }}</td>
                <td>{{ round(($count / $statistics['total_records']) * 100, 2) }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="page-break"></div>

    <!-- Detailed Records -->
    <h3>Detailed Audit Records</h3>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date & Time</th>
                <th>User</th>
                <th>Action</th>
                <th>Table</th>
                <th>Record ID</th>
                <th>Affected User</th>
                <th>IP Address</th>
            </tr>
        </thead>
        <tbody>
            @foreach($audits as $audit)
            <tr>
                <td>{{ $audit->id }}</td>
                <td>{{ $audit->created_at }}</td>
                <td>{{ $audit->user_name ?? 'Unknown' }}</td>
                <td>
                    @php
                        $badgeClass = [
                            'INSERT' => 'badge-success',
                            'UPDATE' => 'badge-info',
                            'DELETE' => 'badge-danger',
                            'LOGIN' => 'badge-primary',
                            'LOGOUT' => 'badge-secondary'
                        ][$audit->action] ?? 'badge-secondary';
                    @endphp
                    <span class="badge {{ $badgeClass }}">{{ $audit->action }}</span>
                </td>
                <td>{{ $audit->table_name }}</td>
                <td>{{ $audit->record_id }}</td>
                <td>{{ !empty(trim($audit->affected_user_name)) ? $audit->affected_user_name : 'N/A' }}</td>
                <td>{{ $audit->ip_address }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>This is a system-generated report. Page <span class="pagenum"></span></p>
        <p>Confidential - For authorized use only</p>
    </div>
</body>
</html>